NDefines.NCountry.CULTURAL_UNION_MIN_DEV = 750						-- Minimum development to get cultural union effect without Common Sense, or if CULTURAL_UNION_MIN_RANK is set to negative value.
NDefines.NCountry.CULTURAL_UNION_MIN_RANK = 5						-- Minimum rank to get cultural union effect with Common Sense.
NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 3							-- Capital must have at least this much development to be a free city
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 75			-- Need at least this much development to upgrade to government rank 2
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 150			-- Need at least this much development to upgrade to government rank 3
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_4 = 500			-- Need at least this much development to upgrade to government rank 4
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_5 = 850			-- Need at least this much development to upgrade to government rank 5
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_6 = 1200			-- Need at least this much development to upgrade to government rank 6
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_2 = 5
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_3 = 5
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_4 = 5
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_5 = 5
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_6 = 5
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 10
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 10
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_4 = 10
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_5 = 10
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_6 = 10
NDefines.NCountry.HRE_RANK = 5										-- Emperor of the HRE is displayed as this rank (for ruler title only)
NDefines.NCountry.HRE_MAX_RANK = 2									-- for members
NDefines.NCountry.HRE_MAX_RANK_ELECTOR = 3							-- for electors
NDefines.NCountry.MAX_GOV_RANK = 6
NDefines.NCountry.ADDITIONAL_MIN_DEVELOPMENT_FOR_GOV_RANK_X = 350
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_X = 5
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_X = 10
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 3

NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 100 			-- Countries with more total development than this cannot be vassalized
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 200 				-- Countries with more total development than this cannot be made into a march
NDefines.NDiplomacy.MARCH_DEVELOPMENT_FRACTION = 0.25
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 50					-- Number of years before a union can be integrated
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 10				-- Number of years before a vassal can be integrated

NDefines.NNationDesigner.MAX_GOVERNMENT_RANK = 6
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_1 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_2 = 5
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_3 = 10
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_4 = 15
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_5 = 20
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_6 = 25